// Regenerates src/http/fonts.ts: the bundled IBM Plex Mono woff2 (Latin subset,
// weights 400/500/600) embedded as base64, plus a short content hash per weight.
//
// Usage: node scripts/gen-fonts.mjs   (or: npm run gen:fonts)
//
// Fetches the woff2 from a pinned Fontsource release so the daemon ships no
// binary assets and regeneration is reproducible (bump FONT_VERSION to update).
// The per-weight hash is what the dashboard puts in each font URL
// (/assets/fonts/ibm-plex-mono-<w>.<hash>.woff2) so the immutable one-year cache
// is safe: regenerating the font changes the hash, which changes the URL, which
// busts every client cache.
//
// IBM Plex Mono is licensed under the SIL Open Font License 1.1; the full license
// and copyright notice ship in licenses/IBM-Plex-Mono-OFL.txt (source:
// https://github.com/IBM/plex).

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Pinned so regeneration is reproducible; bump to adopt a newer Fontsource build.
const FONT_VERSION = "5.2.7";
const CDN = `https://cdn.jsdelivr.net/fontsource/fonts/ibm-plex-mono@${FONT_VERSION}`;
// Full digests for the exact Fontsource release artifacts. Update these only
// after reviewing the new font bytes when bumping FONT_VERSION.
const FONT_SOURCES = [
  {
    weight: "400",
    sha256: "08949f728dc52d528e69b1667d15c89a5686a4ee9a296ff90983985f99c380f7"
  },
  {
    weight: "500",
    sha256: "01d285447409c8a588692162439a038b8cbd7871309ee20267b0d2d91c6e8e22"
  },
  {
    weight: "600",
    sha256: "0d1f0b8d0722224e32e9f28261bdc86c79115be73444ae5eceb73976a1bcdf83"
  }
];
const OUT = fileURLToPath(new URL("../src/http/fonts.ts", import.meta.url));

async function fetchWoff2({ weight, sha256: expectedSha256 }) {
  const url = `${CDN}/latin-${weight}-normal.woff2`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`fetch ${url} failed: ${res.status} ${res.statusText}`);
  }
  const bytes = Buffer.from(await res.arrayBuffer());
  if (bytes.subarray(0, 4).toString("latin1") !== "wOF2") {
    throw new Error(`fetched ${url} is not a woff2 file`);
  }
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  if (sha256 !== expectedSha256) {
    throw new Error(
      `${url} SHA-256 mismatch: expected ${expectedSha256}, got ${sha256}`
    );
  }
  return { bytes, sha256 };
}

const fonts = [];
for (const source of FONT_SOURCES) {
  const { weight } = source;
  const { bytes, sha256 } = await fetchWoff2(source);
  fonts.push({
    weight,
    base64: bytes.toString("base64"),
    hash: sha256.slice(0, 8)
  });
  console.log(
    `fetched ${weight}: ${bytes.length} bytes, hash ${fonts.at(-1).hash}`
  );
}

const L = [];
L.push("// AUTO-GENERATED by scripts/gen-fonts.mjs — do not hand-edit.");
L.push(
  "// Run `npm run gen:fonts` (or `node scripts/gen-fonts.mjs`) to regenerate."
);
L.push(
  "// Bundled IBM Plex Mono (SIL Open Font License 1.1), Latin subset, weights"
);
L.push(
  "// 400/500/600, embedded as base64 so the daemon dashboard is self-contained and"
);
L.push(
  "// works offline. Full license + copyright: licenses/IBM-Plex-Mono-OFL.txt."
);
L.push(
  `// Source: https://github.com/IBM/plex via Fontsource ibm-plex-mono@${FONT_VERSION}.`
);
L.push("");
L.push('type BundledFontWeight = "400" | "500" | "600";');
L.push("");
L.push("type BundledFont = {");
L.push("  weight: BundledFontWeight;");
L.push("  hash: string;");
L.push("};");
L.push("");
L.push("// Weight + content hash pairs, in @font-face declaration order.");
L.push("export const BUNDLED_FONTS: readonly BundledFont[] = [");
for (const f of fonts) {
  L.push(`  { weight: "${f.weight}", hash: "${f.hash}" },`);
}
L[L.length - 1] = L[L.length - 1].replace(/,$/, "");
L.push("];");
L.push("");
L.push("const FONT_HASH: Record<BundledFontWeight, string> = {");
for (const f of fonts) {
  L.push(`  "${f.weight}": "${f.hash}",`);
}
L[L.length - 1] = L[L.length - 1].replace(/,$/, "");
L.push("};");
L.push("");
L.push("const FONT_BASE64: Record<BundledFontWeight, string> = {");
for (const f of fonts) {
  L.push(`  "${f.weight}":`);
  L.push(`    "${f.base64}",`);
}
L[L.length - 1] = L[L.length - 1].replace(/,$/, "");
L.push("};");
L.push("");
L.push("const decoded = new Map<BundledFontWeight, ArrayBuffer>();");
L.push("");
L.push("function isBundledWeight(value: string): value is BundledFontWeight {");
L.push('  return value === "400" || value === "500" || value === "600";');
L.push("}");
L.push("");
L.push(
  "/** Short content hash for a bundled weight, or undefined if unknown. */"
);
L.push("export function getFontHash(weight: string): string | undefined {");
L.push("  return isBundledWeight(weight) ? FONT_HASH[weight] : undefined;");
L.push("}");
L.push("");
L.push("/**");
L.push(
  " * Decoded woff2 bytes for a bundled IBM Plex Mono weight, or undefined for an"
);
L.push(
  " * unknown weight. Decoding is memoized so each weight is decoded at most once,"
);
L.push(" * and the returned ArrayBuffer is a valid Response body.");
L.push(" */");
L.push(
  "export function getBundledFont(weight: string): ArrayBuffer | undefined {"
);
L.push("  if (!isBundledWeight(weight)) {");
L.push("    return undefined;");
L.push("  }");
L.push("  let bytes = decoded.get(weight);");
L.push("  if (bytes === undefined) {");
L.push('    const buffer = Buffer.from(FONT_BASE64[weight], "base64");');
L.push("    bytes = buffer.buffer.slice(");
L.push("      buffer.byteOffset,");
L.push("      buffer.byteOffset + buffer.byteLength");
L.push("    );");
L.push("    decoded.set(weight, bytes);");
L.push("  }");
L.push("  return bytes;");
L.push("}");
L.push("");

// Every remote payload reaching this sink matched its pinned full SHA-256 above.
// codeql[js/http-to-file-access]
writeFileSync(OUT, L.join("\n"));
console.log(`wrote ${OUT}`);
