const SINGLE_AGENT_PR = [
  "name: builtin_single_agent_pr",
  "entry: agent",
  "inputs:",
  "  provider:",
  "    type: provider",
  "    default: codex",
  "  prompt:",
  "    type: path",
  "    default: WORKFLOW.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  agent:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ provider }}"',
  '      prompt: "{{ prompt }}"',
  "    transitions:",
  "      - to: done",
  "        when:",
  "          provider_success: true",
  "          branch_ahead_of_base: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const PLAN_TDD_PR = [
  "name: builtin_plan_tdd_pr",
  "entry: planning",
  "inputs:",
  "  planner:",
  "    type: provider",
  "    default: codex",
  "  implementer:",
  "    type: provider",
  "    default: codex",
  "  plan_prompt:",
  "    type: path",
  "    default: prompts/plan.md",
  "  impl_prompt:",
  "    type: path",
  "    default: prompts/impl.md",
  "  plan_artifact:",
  "    type: path",
  "    default: PLAN.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  planning:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ planner }}"',
  '      prompt: "{{ plan_prompt }}"',
  "    transitions:",
  "      - to: implementing",
  "        when:",
  "          provider_success: true",
  '          artifact_exists: "{{ plan_artifact }}"',
  "      - to: failed",
  "  implementing:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ implementer }}"',
  '      prompt: "{{ impl_prompt }}"',
  "    transitions:",
  "      - to: done",
  "        when:",
  "          provider_success: true",
  "          branch_ahead_of_base: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const REFACTOR_SWARM = [
  "name: builtin_refactor_swarm",
  "entry: red_team",
  "inputs:",
  "  red_teamer:",
  "    type: provider",
  "    default: codex",
  "  refactorer:",
  "    type: provider",
  "    default: codex",
  "  verifier:",
  "    type: provider",
  "    default: codex",
  "  red_team_prompt:",
  "    type: path",
  "    default: prompts/red-team.md",
  "  refactor_prompt:",
  "    type: path",
  "    default: prompts/refactor.md",
  "  verify_prompt:",
  "    type: path",
  "    default: prompts/verify.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  red_team:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ red_teamer }}"',
  '      prompt: "{{ red_team_prompt }}"',
  "    transitions:",
  "      - to: refactoring",
  "        when:",
  "          provider_success: true",
  "          branch_advanced_since_attempt_start: true",
  "          branch_ahead_of_base: true",
  "      - to: failed",
  "  refactoring:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ refactorer }}"',
  '      prompt: "{{ refactor_prompt }}"',
  "    transitions:",
  "      - to: verifying",
  "        when:",
  "          provider_success: true",
  "          branch_advanced_since_attempt_start: true",
  "          branch_ahead_of_base: true",
  "      - to: failed",
  "  verifying:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ verifier }}"',
  '      prompt: "{{ verify_prompt }}"',
  "    transitions:",
  "      - to: done",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const AUTOFIX_UNTIL_CLEAN = [
  "name: builtin_autofix_until_clean",
  "entry: waiting",
  "inputs:",
  "  provider:",
  "    type: provider",
  "    default: codex",
  "  fix_prompt:",
  "    type: path",
  "    default: prompts/autofix.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  waiting:",
  "    action:",
  "      kind: wait",
  "    transitions:",
  "      - to: done",
  "        when:",
  "          checks: success",
  "          unresolved_review_threads: 0",
  "      - to: failed",
  "        when:",
  "          checks: failure",
  "      - to: autofix",
  "        when:",
  "          checks: success",
  "  autofix:",
  "    action:",
  "      kind: agent",
  '      provider: "{{ provider }}"',
  '      prompt: "{{ fix_prompt }}"',
  "    transitions:",
  "      - to: waiting",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const MERGE_WHEN_GREEN = [
  "name: builtin_merge_when_green",
  "entry: merging",
  "inputs:",
  "  method:",
  "    type: string",
  "    default: squash",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  merging:",
  "    action:",
  "      kind: merge_pr",
  '      method: "{{ method }}"',
  "    transitions:",
  "      - to: done",
  "        when:",
  "          pr_merged: true",
  "      - to: failed",
  "        when:",
  "          pr_open: false",
  "      - to: failed",
  "        when:",
  "          checks: failure",
  "      - to: failed",
  "        when:",
  "          mergeable: false",
  "      # Deliberately no catch-all: readiness deferrals stay parked, while",
  "      # deterministic merge refusals are terminalized by reconciliation.",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

export const BUILTIN_WORKFLOW_TEMPLATES: Readonly<Record<string, string>> = {
  "autofix-until-clean": AUTOFIX_UNTIL_CLEAN,
  "merge-when-green": MERGE_WHEN_GREEN,
  "plan-tdd-pr": PLAN_TDD_PR,
  "refactor-swarm": REFACTOR_SWARM,
  "single-agent-pr": SINGLE_AGENT_PR
};
