const SINGLE_AGENT_PR = [
  "name: builtin_single_agent_pr",
  "entry: agent",
  "inputs:",
  "  provider:",
  "    type: provider",
  "    default: codex",
  "  prompt:",
  "    type: path",
  "    default: WORKFLOW.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  agent:",
  "    action:",
  "      kind: agent",
  "      provider: \"{{ provider }}\"",
  "      prompt: \"{{ prompt }}\"",
  "    complete_when:",
  "      provider_success: true",
  "      branch_ahead_of_base: true",
  "    transitions:",
  "      - to: done",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const PLAN_TDD_PR = [
  "name: builtin_plan_tdd_pr",
  "entry: planning",
  "inputs:",
  "  planner:",
  "    type: provider",
  "    default: codex",
  "  implementer:",
  "    type: provider",
  "    default: codex",
  "  plan_prompt:",
  "    type: path",
  "    default: prompts/plan.md",
  "  impl_prompt:",
  "    type: path",
  "    default: prompts/impl.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  planning:",
  "    action:",
  "      kind: agent",
  "      provider: \"{{ planner }}\"",
  "      prompt: \"{{ plan_prompt }}\"",
  "    complete_when:",
  "      artifact_exists: PLAN.md",
  "      provider_success: true",
  "    transitions:",
  "      - to: implementing",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  implementing:",
  "    action:",
  "      kind: agent",
  "      provider: \"{{ implementer }}\"",
  "      prompt: \"{{ impl_prompt }}\"",
  "    complete_when:",
  "      provider_success: true",
  "      branch_ahead_of_base: true",
  "    transitions:",
  "      - to: done",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const AUTOFIX_UNTIL_CLEAN = [
  "name: builtin_autofix_until_clean",
  "entry: waiting",
  "inputs:",
  "  provider:",
  "    type: provider",
  "    default: codex",
  "  fix_prompt:",
  "    type: path",
  "    default: prompts/autofix.md",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  waiting:",
  "    action:",
  "      kind: wait",
  "    transitions:",
  "      - to: done",
  "        when:",
  "          checks: success",
  "          unresolved_review_threads: 0",
  "      - to: autofix",
  "        when:",
  "          unresolved_review_threads: 1",
  "      - to: failed",
  "        when:",
  "          checks: failure",
  "  autofix:",
  "    action:",
  "      kind: agent",
  "      provider: \"{{ provider }}\"",
  "      prompt: \"{{ fix_prompt }}\"",
  "    complete_when:",
  "      provider_success: true",
  "      branch_ahead_of_base: true",
  "    transitions:",
  "      - to: waiting",
  "        when:",
  "          provider_success: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

const MERGE_WHEN_GREEN = [
  "name: builtin_merge_when_green",
  "entry: waiting",
  "inputs:",
  "  method:",
  "    type: string",
  "    default: squash",
  "exits:",
  "  success: done",
  "  blocked: failed",
  "states:",
  "  waiting:",
  "    action:",
  "      kind: wait",
  "    transitions:",
  "      - to: merging",
  "        when:",
  "          checks: success",
  "          mergeable: true",
  "          unresolved_review_threads: 0",
  "      - to: failed",
  "        when:",
  "          checks: failure",
  "      - to: failed",
  "        when:",
  "          mergeable: false",
  "  merging:",
  "    action:",
  "      kind: merge_pr",
  "      method: \"{{ method }}\"",
  "    transitions:",
  "      - to: done",
  "        when:",
  "          pr_merged: true",
  "      - to: failed",
  "  done:",
  "    exit: success",
  "    terminal: success",
  "  failed:",
  "    exit: blocked",
  "    terminal: blocked",
  ""
].join("\n");

export const BUILTIN_WORKFLOW_TEMPLATES: Readonly<Record<string, string>> = {
  "autofix-until-clean": AUTOFIX_UNTIL_CLEAN,
  "merge-when-green": MERGE_WHEN_GREEN,
  "plan-tdd-pr": PLAN_TDD_PR,
  "single-agent-pr": SINGLE_AGENT_PR
};
